### ISSUE TITLE
`Parsing: Read length of mdat which is less than 8 bytes: 1`

### ISSUE THREAD

**Issue by probablykasper** [Saecki/rust-mp4ameta#17]
Hi, I'm getting this error from `Tag::read_from_path()`: `Parsing: Read length of mdat which is less than 8 bytes: 1`. iTunes, QuickTime, VLC and [music-metadata](https://github.com/Borewit/music-metadata) are able to handle the file just fine.

I tested mp4ameta on 4 of the `m4a`s I have, and this issue turned up, so not sure how common this error would be for the other 4000 `m4a`s I've got.

Can send over the m4a privately if you need it.

**Comment by Saecki** [comment]
Hi thanks for reporting this bug. The file would be very helpful indeed, so if you could send it over that would be great.

**Comment by probablykasper** [comment]
@Saecki Sent it to your email

**Comment by Saecki** [comment]
Funny thing on the `dev` branch I was already implementing support for 64bit atom sizes, which are denoted by the length of `1` which would otherwise illegal. I had not tested it yet though it seems to work just fine on the file you sent me. Currently only reading is supported but I will merge these changes into master for now.

**Comment by probablykasper** [comment]
@Saecki Ah that's great! Tried using commit b7753ac4cf7bd744178fd74fefb8d15bf4fcde01 to read, and it worked.
