### ISSUE TITLE
Two types of errors on real-world m4a file metadata

### ISSUE THREAD

**Issue by rayrrr** [Saecki/rust-mp4ameta#2]
Hello again, after the previous fix for #1 I am now encountering two distinct kinds of errors with all the M4A files in my collection, either

`Parsing: Typed data head to short`

or

`UnknownDataType(21): Unknown datatype code`

I am providing two test files, one that produces each of the above errors, at https://github.com/rayrrr/rust-mp4ameta/tree/master/test_files so please advise. Thank you again for your efforts.

**Comment by rayrrr** [comment]
I will attempt a Pull Request myself here but happy to let you fix it as well. I see the error messages were emitted by the `data.rs` file in this crate and am digging in. First question: should https://github.com/Saecki/rust-mp4ameta/blob/master/src/data.rs#L35 read `Unparsed(u32)` instead of `i32` as per the comment directly above it?

**Comment by Saecki** [comment]
Sorry, I am only seeing this now. The the comment on the `Unparsed(i32)` should be `i32` since -1 represents typed data which datatype is yet to be read in the first 4 bytes of a data atoms content.
The 21 in `UnknownDataType(21): Unknown datatype code` error stands for a `BE Signed Integer` according to [this](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/Metadata/Metadata.html#//apple_ref/doc/uid/TP40000939-CH1-SW34) table, which should probably be implemented. But I would need to know for which tags this datatype is showing up.

**Comment by Saecki** [comment]
Sorry, I am only seeing this now. 
`Parsing: Typed data head to short` 

The 21 in `UnknownDataType(21): Unknown datatype code` error stands for a `BE Signed Integer` according to (this)[https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/Metadata/Metadata.html#//apple_ref/doc/uid/TP40000939-CH1-SW34] table, which should probably be implemented. But I would need to know for which tags this datatype is showing up. 

The the comment on the `Unparsed(i32)` should be `i32` since `-1` represents typed data which datatype is yet to be read in the first 4 bytes of a `data atoms` content.

Thanks for reporting, I'm at it.

**Comment by Saecki** [comment]
Oh I took a look at your changes and saw you already implemented most of what I said so this probably sounded a bit ignorant. I will try to merge your current changes and fix it from there.

**Comment by rayrrr** [comment]
Caveat emptor...I am very new to Rust and my fork is not compiling in its current state. I am sure I correctly transcribed the additional atom constants but that's about all I can guarantee. Thank you for working on this.

**Comment by Saecki** [comment]
I created a [bugfix](https://github.com/Saecki/rust-mp4ameta/tree/bugfix) branch which at least compiles now.

**Comment by rayrrr** [comment]
Definite progress on that bugfix branch. The ones that used to panic with `UnknownDataType(21): Unknown datatype code` are being handled correctly. And now the other one is returning a more detailed panic error:

`Parsing: Error reading moov: Error reading udta: Error reading meta: Error reading ilst: Error reading ©wrt: Error reading data: Typed data head to short', src/main.rs:5:17`

Wishing you luck and looking forward to the next version bump. Thank you so much!

**Comment by Saecki** [comment]
I think I found the bug, I was incorrectly checking if typed data was > 8 instead of >= 8. So empty data atoms would result in the `Parsing: Typed data head to short` error. If this works for you I will merge it into master and bump the version number.

**Comment by Saecki** [comment]
Version 0.2.2 containing these fixes is now published.

**Comment by rayrrr** [comment]
It is now working correctly with all the files that were exhibiting these errors. Thanks so much @Saecki !
